//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_First_Winform_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Log
    {
        public int Entry_Log_ID { get; set; }
        public string First_Name { get; set; }
        public string Middle_Initial { get; set; }
        public string Last_Name { get; set; }
        public string Licence_Plate_Number { get; set; }
        public System.DateTime Time_In { get; set; }
        public System.DateTime Time_Out { get; set; }
        public bool Laptop { get; set; }
        public string Category { get; set; }
        public string Created_By { get; set; }
    }
}
